name: zine

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: local
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=reverse-proxy"
      - "traefik.http.routers.web.rule=PathPrefix(`/`)"
      - "traefik.http.routers.web.service=web"
      - "traefik.http.services.web.loadbalancer.server.port=3000"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    hostname: web
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    driver: bridge
    name: reverse-proxy
